### ISSUE TITLE
Crash Exception preparing structure feature (Strongholds)

### ISSUE THREAD

**Issue by NLBlackEagle** [fonnymunkey/RLCraft-Dregora-Edition#13]
---- Minecraft Crash Report ----
// Crash report modified by FermiumASM.
// FermiumASM deobfuscated this stacktrace using MCP's stable-39 mappings.
// I bet Cylons wouldn't have this problem.

Time: 2024-08-06 20:12:02 CEST
Description: Exception preparing structure feature

java.lang.NullPointerException: Exception preparing structure feature
    at com.pg85.otg.forge.biomes.OTGBiomeProvider.findBiomePosition(OTGBiomeProvider.java:137)
    at com.pg85.otg.forge.generator.structure.OTGStrongholdGen.generatePositions(OTGStrongholdGen.java:133)
    at com.pg85.otg.forge.generator.structure.OTGStrongholdGen.canSpawnStructureAtCoords(OTGStrongholdGen.java:88)
    at net.minecraft.world.gen.structure.MapGenStructure.recursiveGenerate(MapGenStructure.java:38)
    at net.minecraft.world.gen.MapGenBase.generate(SourceFile:34)
    at ivorius.reccomplex.world.gen.feature.structure.MapGenStructureHook.generate(MapGenStructureHook.java:153)
    at ivorius.reccomplex.events.handlers.RCTerrainGenEventHandler$5.generate(RCTerrainGenEventHandler.java:329)
    at com.pg85.otg.forge.world.ForgeWorld.prepareDefaultStructures(ForgeWorld.java:945)
    at com.pg85.otg.generator.ChunkProviderOTG.generate(ChunkProviderOTG.java:132)
    at com.pg85.otg.forge.generator.OTGChunkGenerator.getBlocks(OTGChunkGenerator.java:259)
    at com.pg85.otg.forge.generator.OTGChunkGenerator.generateChunk(OTGChunkGenerator.java:129)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:143)
    at net.minecraft.server.MinecraftServer.initialWorldChunkLoad(MinecraftServer.java:344)
    at net.minecraft.server.integrated.IntegratedServer.loadAllWorlds(IntegratedServer.java:210)
    at net.minecraft.server.integrated.IntegratedServer.init(IntegratedServer.java:233)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
    at java.lang.Thread.run(Thread.java:745)

**Comment by NLBlackEagle** [comment]
Error post for documentation purposes due to a misleading report, Issue is caused by river biomes not properly inheriting and making it so the stronghold generation fails when it tries to register.
