### ISSUE TITLE
Crash immediately after creating OTG world

### ISSUE THREAD

**Issue by PurplePrint** [fonnymunkey/RLCraft-Dregora-Edition#14]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into [x]◀️

- [x] v1.0.0 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.
Crash immediately after creating OTG world

```
java.lang.NullPointerException: Exception in server tick loop
	at com.pg85.otg.forge.materials.ForgeMaterialData.parseForWorld(ForgeMaterialData.java:448)
	at com.pg85.otg.configuration.biome.settings.ReplacedBlocksMatrix.parseForWorld(ReplacedBlocksMatrix.java:309)
	at com.pg85.otg.network.ServerConfigProvider.createAndRegisterBiome(ServerConfigProvider.java:737)
	at com.pg85.otg.network.ServerConfigProvider.indexSettings(ServerConfigProvider.java:652)
	at com.pg85.otg.network.ServerConfigProvider.loadBiomes(ServerConfigProvider.java:229)
	at com.pg85.otg.network.ServerConfigProvider.loadSettings(ServerConfigProvider.java:145)
	at com.pg85.otg.network.ServerConfigProvider.<init>(ServerConfigProvider.java:84)
	at com.pg85.otg.forge.world.WorldLoader.getOrCreateForgeWorld(WorldLoader.java:361)
	at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:158)
	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:121)
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by NLBlackEagle** [comment]
Did you install through the curseforge installer and read the readme file included with the server pack?
