### ISSUE TITLE
Unable to start the server normally

### ISSUE THREAD

**Issue by fishlanding** [fonnymunkey/RLCraft-Dregora-Edition#29]
#### RLCraft Dregora Server/Client
▶️Please specify if it's about the Dregora Server pack or Clientside installation by placing "x" into []◀️
- [ ] Clientside
- [x] Serverside

#### Dregora Version
▶️Please specify the Dregora version that you are running by placing "x" into []◀️

- [ ] v1.0.0 RLCraft Dregora
- [x] v1.0.1 RLCraft Dregora

#### Description
▶️What is happening? - Explain what happens and what steps should be done to reproduce the issue.

[21:18:40] [Server thread/INFO] [FML]: Forge Mod Loader has successfully loaded 177 mods
[21:18:42] [Server thread/INFO] [dimstack]: Dimension stack configuration file for world DregoraRL sucessfully loaded.
[21:18:42] [Server thread/INFO] [net.minecraft.server.dedicated.DedicatedServer]: Preparing level "DregoraRL"
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: com.pg85.otg.shaded.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (File); line: 1, column: 1]
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.shaded.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.shaded.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4145)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.shaded.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4000)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.shaded.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2902)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.configuration.dimensions.DimensionsConfig.loadFromFile(DimensionsConfig.java:344)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:69)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.world.WorldProvider.func_76572_b(WorldProvider.java:58)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.world.WorldProvider.func_76558_a(WorldProvider.java:40)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:298)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:270)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
[21:18:43] [Server thread/INFO] [STDERR]: [com.pg85.otg.configuration.dimensions.DimensionsConfig:loadFromFile:346]: 	at java.lang.Thread.run(Unknown Source)
[21:18:43] [Server thread/WARN] [OTG]: Failed to load E:\RLC-D\.\DregoraRL\OpenTerrainGenerator\Config.yaml, trying to load backup.
[21:18:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.RuntimeException: OTG encountered a critical error loading E:\RLC-D\.\DregoraRL\OpenTerrainGenerator\Config.yaml and could not load a backup, exiting.OTG automatically backs up files before writing and tries to use the backup when loading. If your world's Config.yaml and its backup have been corrupted, you can replace it with your own backup or create a new world with the same dimensions and copy its Config.yaml (edit the WorldName node if necessary).
	at com.pg85.otg.configuration.dimensions.DimensionsConfig.loadFromFile(DimensionsConfig.java:395) ~[DimensionsConfig.class:?]
	at com.pg85.otg.forge.world.OTGWorldType.getBiomeProvider(OTGWorldType.java:69) ~[OTGWorldType.class:?]
	at net.minecraft.world.WorldProvider.init(WorldProvider.java:58) ~[aym.class:?]
	at net.minecraft.world.WorldProvider.setWorld(WorldProvider.java:40) ~[aym.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:116) ~[oo.class:?]
	at net.minecraft.server.MinecraftServer.loadAllWorlds(MinecraftServer.java:298) ~[MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:270) ~[nz.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_431]
[21:18:43] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: E:\RLC-D\.\crash-reports\crash-2024-10-23_21.18.43-server.txt
[21:18:43] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[21:18:43] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[21:18:43] [Server thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds
[21:18:43] [Server thread/INFO] [FML]: The state engine was in incorrect state SERVER_STARTING and forced into state SERVER_STOPPED. Errors may have been discarded.
[21:18:43] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Stopping server
[21:18:43] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving players
[21:18:43] [Server Shutdown Thread/INFO] [net.minecraft.server.MinecraftServer]: Saving worlds

There is the whole log:)
[latest.log](https://github.com/user-attachments/files/17492120/latest.log)

**Comment by fishlanding** [comment]
I found that there is no content in the files of this path `.\DregoraRL\OpenTerrainGenerator\Config.yaml`, which may have caused the crash.

**Comment by fonnymunkey** [comment]
Try deleting the folders inside /mods/OpenTerrainGenerator/ and letting them reinstall on launch

**Comment by fishlanding** [comment]
[latest.log](https://github.com/user-attachments/files/17495556/latest.log)
I deleted the folder in this path and restarted the server, but it still crashed, and the logs are the same.

**Comment by fonnymunkey** [comment]
Try renaming your world file and let it generate a new one.
If it generates fine, you can try to copy the DregoraRL/OpenTerrainGenerator/Config.yaml and Config-backup.yaml file from the new world into the old one and name it back, if nothing else was corrupted it should work.
